# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/collision.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/collision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(aimdk/protocol/mc/motion/collision.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\"Q\n\x10\x43ollisionRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\"d\n\x11\x43ollisionResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12\x1f\n\x17\x43ollisionDetectionState\x18\x02 \x01(\x08\"U\n\x10\x44\x61nceTypeRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x12\n\ndance_name\x18\x02 \x01(\t\"\x9c\x01\n\x0fMcDanceResponce\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12\x12\n\ndance_name\x18\x02 \x03(\t\x12\x18\n\x10\x64\x61nce_model_path\x18\x03 \x03(\t\x12\x17\n\x0f\x64\x61nce_data_path\x18\x04 \x03(\t\x12\x12\n\ndance_time\x18\x05 \x03(\x01P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.collision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLISIONREQUEST']._serialized_start=96
  _globals['_COLLISIONREQUEST']._serialized_end=177
  _globals['_COLLISIONRESPONSE']._serialized_start=179
  _globals['_COLLISIONRESPONSE']._serialized_end=279
  _globals['_DANCETYPEREQUEST']._serialized_start=281
  _globals['_DANCETYPEREQUEST']._serialized_end=366
  _globals['_MCDANCERESPONCE']._serialized_start=369
  _globals['_MCDANCERESPONCE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
