# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/locomotion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/locomotion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)aimdk/protocol/mc/motion/locomotion.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\"\x90\x01\n\x12LocomotionVelocity\x12,\n\x04mode\x18\x01 \x01(\x0e\x32\x1e.aimdk.protocol.LocomotionMode\x12\x18\n\x10\x66orward_velocity\x18\x02 \x01(\x01\x12\x18\n\x10lateral_velocity\x18\x03 \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x04 \x01(\x01\"x\n\x15LocomotionGaitRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x30\n\x04gait\x18\x02 \x01(\x0e\x32\".aimdk.protocol.LocomotionGaitType\"z\n\x16LocomotionGaitResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12\x30\n\x04gait\x18\x02 \x01(\x0e\x32\".aimdk.protocol.LocomotionGaitType*\x88\x02\n\x12LocomotionGaitType\x12\x1e\n\x1aLocomotionGaitType_UNKNOWN\x10\x00\x12\x1d\n\x19LocomotionGaitType_STANCE\x10\x01\x12\x1b\n\x17LocomotionGaitType_WALK\x10\x02\x12!\n\x1dLocomotionGaitType_SMART_WALK\x10\x03\x12\x1e\n\x1aLocomotionGaitType_TERRAIN\x10\x04\x12\x1a\n\x16LocomotionGaitType_RUN\x10\x05\x12\x1b\n\x17LocomotionGaitType_JUMP\x10\x06\x12\x1a\n\x16LocomotionGaitType_HOP\x10\x07*K\n\x0eLocomotionMode\x12\x1a\n\x16LocomotionMode_DEFAULT\x10\x00\x12\x1d\n\x19LocomotionMode_NAVIGATION\x10\x01P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.locomotion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCOMOTIONGAITTYPE']._serialized_start=491
  _globals['_LOCOMOTIONGAITTYPE']._serialized_end=755
  _globals['_LOCOMOTIONMODE']._serialized_start=757
  _globals['_LOCOMOTIONMODE']._serialized_end=832
  _globals['_LOCOMOTIONVELOCITY']._serialized_start=98
  _globals['_LOCOMOTIONVELOCITY']._serialized_end=242
  _globals['_LOCOMOTIONGAITREQUEST']._serialized_start=244
  _globals['_LOCOMOTIONGAITREQUEST']._serialized_end=364
  _globals['_LOCOMOTIONGAITRESPONSE']._serialized_start=366
  _globals['_LOCOMOTIONGAITRESPONSE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
