# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/mc_adjust.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/mc_adjust.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import scalar_trajectory_pb2 as aimdk_dot_protocol_dot_common_dot_scalar__trajectory__pb2
from aimdk.protocol.common import rpc_pb2 as aimdk_dot_protocol_dot_common_dot_rpc__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.common import se3_pose_pb2 as aimdk_dot_protocol_dot_common_dot_se3__pose__pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.quaternion_pb2
try:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_rpy__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.rpy_pb2
from aimdk.protocol.mc.common import planning_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_planning__pb2
from aimdk.protocol.mc.motion import motion_param_pb2 as aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_velocity_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_acceleration_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.quaternion_pb2

from aimdk.protocol.common.scalar_trajectory_pb2 import *
from aimdk.protocol.common.rpc_pb2 import *
from aimdk.protocol.common.se3_pose_pb2 import *
from aimdk.protocol.mc.common.planning_pb2 import *
from aimdk.protocol.mc.motion.motion_param_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(aimdk/protocol/mc/motion/mc_adjust.proto\x12\x0e\x61imdk.protocol\x1a-aimdk/protocol/common/scalar_trajectory.proto\x1a\x1f\x61imdk/protocol/common/rpc.proto\x1a$aimdk/protocol/common/se3_pose.proto\x1a\'aimdk/protocol/mc/common/planning.proto\x1a+aimdk/protocol/mc/motion/motion_param.proto\"\xb5\x01\n\rAdjustCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x61rm_type\x18\x02 \x01(\r\x12\x35\n\x04mode\x18\x03 \x01(\x0e\x32\'.aimdk.protocol.AdjustCommand.PressType\x12\x0c\n\x04step\x18\x04 \x01(\x01\x12\x10\n\x08velocity\x18\x05 \x01(\x01\"-\n\tPressType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05Short\x10\x01\x12\x08\n\x04Long\x10\x02\"u\n\x14\x41\x64justCommandRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12.\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x1d.aimdk.protocol.AdjustCommand\"\x8a\x01\n\x11\x41\x64justEndPosition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0b\n\x03r_x\x18\x05 \x01(\x01\x12\x0b\n\x03r_y\x18\x06 \x01(\x01\x12\x0b\n\x03r_z\x18\x07 \x01(\x01\x12\x1f\n\x17\x61round_singularity_flag\x18\x08 \x01(\x08\"\x85\x01\n\x1a\x41\x64justEndPositionsResponse\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x38\n\rend_positions\x18\x02 \x03(\x0b\x32!.aimdk.protocol.AdjustEndPositionP\x00P\x01P\x02P\x03P\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.mc_adjust_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADJUSTCOMMAND']._serialized_start=265
  _globals['_ADJUSTCOMMAND']._serialized_end=446
  _globals['_ADJUSTCOMMAND_PRESSTYPE']._serialized_start=401
  _globals['_ADJUSTCOMMAND_PRESSTYPE']._serialized_end=446
  _globals['_ADJUSTCOMMANDREQUEST']._serialized_start=448
  _globals['_ADJUSTCOMMANDREQUEST']._serialized_end=565
  _globals['_ADJUSTENDPOSITION']._serialized_start=568
  _globals['_ADJUSTENDPOSITION']._serialized_end=706
  _globals['_ADJUSTENDPOSITIONSRESPONSE']._serialized_start=709
  _globals['_ADJUSTENDPOSITIONSRESPONSE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
