# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/motion_param.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/motion_param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import se3_velocity_pb2 as aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2.aimdk.protocol.common.vec3_pb2
from aimdk.protocol.common import se3_acceleration_pb2 as aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2.aimdk.protocol.common.quaternion_pb2

from aimdk.protocol.common.se3_velocity_pb2 import *
from aimdk.protocol.common.se3_acceleration_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+aimdk/protocol/mc/motion/motion_param.proto\x12\x0e\x61imdk.protocol\x1a(aimdk/protocol/common/se3_velocity.proto\x1a,aimdk/protocol/common/se3_acceleration.proto\"\xb7\x01\n\x0bMotionParam\x12\x16\n\x0evelocity_scale\x18\x01 \x01(\x01\x12\x1a\n\x12\x61\x63\x63\x65leration_scale\x18\x02 \x01(\x01\x12\x35\n\x10max_se3_velocity\x18\x03 \x01(\x0b\x32\x1b.aimdk.protocol.SE3Velocity\x12=\n\x14max_se3_acceleration\x18\x04 \x01(\x0b\x32\x1f.aimdk.protocol.SE3AccelerationP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.motion_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONPARAM']._serialized_start=152
  _globals['_MOTIONPARAM']._serialized_end=335
# @@protoc_insertion_point(module_scope)
