# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/move.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/move.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.common import se3_pose_pb2 as aimdk_dot_protocol_dot_common_dot_se3__pose__pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.quaternion_pb2
try:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk_dot_protocol_dot_common_dot_rpy__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_rpy__pb2 = aimdk_dot_protocol_dot_common_dot_se3__pose__pb2.aimdk.protocol.common.rpy_pb2
from aimdk.protocol.common import scalar_trajectory_pb2 as aimdk_dot_protocol_dot_common_dot_scalar__trajectory__pb2
from aimdk.protocol.mc.common import arm_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_arm__pb2
from aimdk.protocol.mc.common import move_pose_mode_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_move__pose__mode__pb2
from aimdk.protocol.mc.common import planning_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_planning__pb2
from aimdk.protocol.mc.motion import motion_param_pb2 as aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_velocity_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_acceleration_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.quaternion_pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.common.se3_pose_pb2 import *
from aimdk.protocol.common.scalar_trajectory_pb2 import *
from aimdk.protocol.mc.common.arm_pb2 import *
from aimdk.protocol.mc.common.move_pose_mode_pb2 import *
from aimdk.protocol.mc.common.planning_pb2 import *
from aimdk.protocol.mc.motion.motion_param_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#aimdk/protocol/mc/motion/move.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a$aimdk/protocol/common/se3_pose.proto\x1a-aimdk/protocol/common/scalar_trajectory.proto\x1a\"aimdk/protocol/mc/common/arm.proto\x1a-aimdk/protocol/mc/common/move_pose_mode.proto\x1a\'aimdk/protocol/mc/common/planning.proto\x1a+aimdk/protocol/mc/motion/motion_param.proto\"a\n\x10LinearMoveTarget\x12%\n\x04left\x18\x01 \x01(\x0b\x32\x17.aimdk.protocol.SE3Pose\x12&\n\x05right\x18\x02 \x01(\x0b\x32\x17.aimdk.protocol.SE3Pose\"\xd0\x01\n\x11LinearMoveRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12.\n\x05group\x18\x02 \x01(\x0e\x32\x1f.aimdk.protocol.McPlanningGroup\x12*\n\x05param\x18\x03 \x01(\x0b\x32\x1b.aimdk.protocol.MotionParam\x12\x30\n\x06target\x18\x04 \x01(\x0b\x32 .aimdk.protocol.LinearMoveTarget\"\xf8\x01\n\x0fMovePoseRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.aimdk.protocol.ArmType\x12*\n\x04mode\x18\x03 \x01(\x0e\x32\x1c.aimdk.protocol.MovePoseMode\x12*\n\x05param\x18\x04 \x01(\x0b\x32\x1b.aimdk.protocol.MotionParam\x12\x10\n\x08is_block\x18\x05 \x01(\x08\x12%\n\x04pose\x18\x06 \x01(\x0b\x32\x17.aimdk.protocol.SE3Pose\"w\n\x14MoveTrajectoryTarget\x12.\n\x04left\x18\x01 \x01(\x0b\x32 .aimdk.protocol.ScalarTrajectory\x12/\n\x05right\x18\x02 \x01(\x0b\x32 .aimdk.protocol.ScalarTrajectory\"|\n\x15MoveTrajectoryRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x34\n\x06target\x18\x02 \x01(\x0b\x32$.aimdk.protocol.MoveTrajectoryTargetP\x00P\x01P\x02P\x03P\x04P\x05P\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.move_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEARMOVETARGET']._serialized_start=345
  _globals['_LINEARMOVETARGET']._serialized_end=442
  _globals['_LINEARMOVEREQUEST']._serialized_start=445
  _globals['_LINEARMOVEREQUEST']._serialized_end=653
  _globals['_MOVEPOSEREQUEST']._serialized_start=656
  _globals['_MOVEPOSEREQUEST']._serialized_end=904
  _globals['_MOVETRAJECTORYTARGET']._serialized_start=906
  _globals['_MOVETRAJECTORYTARGET']._serialized_end=1025
  _globals['_MOVETRAJECTORYREQUEST']._serialized_start=1027
  _globals['_MOVETRAJECTORYREQUEST']._serialized_end=1151
# @@protoc_insertion_point(module_scope)
