# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/movj.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/movj.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.mc.common import planning_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_planning__pb2
from aimdk.protocol.mc.data import joint_pb2 as aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk.protocol.common.control_source_pb2
try:
  aimdk_dot_protocol_dot_common_dot_joint__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk_dot_protocol_dot_common_dot_joint__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_joint__pb2 = aimdk_dot_protocol_dot_mc_dot_data_dot_joint__pb2.aimdk.protocol.common.joint_pb2
from aimdk.protocol.mc.common import move_pose_mode_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_move__pose__mode__pb2
from aimdk.protocol.mc.motion import motion_param_pb2 as aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__velocity__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_velocity_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_se3__acceleration__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.se3_acceleration_pb2
try:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_vec3__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_vec3__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.vec3_pb2
try:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_quaternion__pb2 = aimdk_dot_protocol_dot_mc_dot_motion_dot_motion__param__pb2.aimdk.protocol.common.quaternion_pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.mc.common.planning_pb2 import *
from aimdk.protocol.mc.data.joint_pb2 import *
from aimdk.protocol.mc.common.move_pose_mode_pb2 import *
from aimdk.protocol.mc.motion.motion_param_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#aimdk/protocol/mc/motion/movj.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a\'aimdk/protocol/mc/common/planning.proto\x1a\"aimdk/protocol/mc/data/joint.proto\x1a-aimdk/protocol/mc/common/move_pose_mode.proto\x1a+aimdk/protocol/mc/motion/motion_param.proto\"\xa8\x01\n\x0bMovJRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12.\n\x05group\x18\x02 \x01(\x0e\x32\x1f.aimdk.protocol.McPlanningGroup\x12*\n\x05param\x18\x03 \x01(\x0b\x32\x1b.aimdk.protocol.MotionParam\x12\x0e\n\x06\x61ngles\x18\x04 \x03(\x01\"\xbc\x03\n\x13JointControlRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12=\n\x05group\x18\x02 \x01(\x0e\x32..aimdk.protocol.JointControlRequest.JointGroup\x12\x39\n\x04\x63mds\x18\x03 \x03(\x0b\x32+.aimdk.protocol.JointControlRequest.Control\x1a\x8a\x01\n\x07\x43ontrol\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x04mode\x18\x02 \x01(\x0e\x32\x30.aimdk.protocol.JointControlRequest.Control.Mode\x12\r\n\x05\x61ngle\x18\x03 \x01(\x01\"\"\n\x04Mode\x12\x0c\n\x08\x41\x42SOLUTE\x10\x00\x12\x0c\n\x08RELATIVE\x10\x01\"o\n\nJointGroup\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08LEFT_ARM\x10\x01\x12\r\n\tRIGHT_ARM\x10\x04\x12\x0c\n\x08\x44UAL_ARM\x10\x07\x12\x0e\n\nWAIST_LIFT\x10\x0b\x12\x0f\n\x0bWAIST_PITCH\x10\x0c\x12\x08\n\x04HEAD\x10\rP\x00P\x01P\x02P\x03P\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.movj_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVJREQUEST']._serialized_start=261
  _globals['_MOVJREQUEST']._serialized_end=429
  _globals['_JOINTCONTROLREQUEST']._serialized_start=432
  _globals['_JOINTCONTROLREQUEST']._serialized_end=876
  _globals['_JOINTCONTROLREQUEST_CONTROL']._serialized_start=625
  _globals['_JOINTCONTROLREQUEST_CONTROL']._serialized_end=763
  _globals['_JOINTCONTROLREQUEST_CONTROL_MODE']._serialized_start=729
  _globals['_JOINTCONTROLREQUEST_CONTROL_MODE']._serialized_end=763
  _globals['_JOINTCONTROLREQUEST_JOINTGROUP']._serialized_start=765
  _globals['_JOINTCONTROLREQUEST_JOINTGROUP']._serialized_end=876
# @@protoc_insertion_point(module_scope)
