# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/motion/stand.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/motion/stand.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$aimdk/protocol/mc/motion/stand.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\"\x93\x01\n\x0cStandRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12\x33\n\x06stance\x18\x02 \x01(\x0e\x32#.aimdk.protocol.StandRequest.Stance\"\x1f\n\x06Stance\x12\n\n\x06\x46REEZE\x10\x00\x12\t\n\x05STAND\x10\x01P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.motion.stand_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STANDREQUEST']._serialized_start=93
  _globals['_STANDREQUEST']._serialized_end=240
  _globals['_STANDREQUEST_STANCE']._serialized_start=209
  _globals['_STANDREQUEST_STANCE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
