#!/usr/bin/env bash

set -euo pipefail

EDGE_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${EDGE_ROOT}/env.sh"

# Prefer ONNX generated by export_onnx.sh so `export -> build` is a real
# pipeline for a brand-new checkpoint. Fall back to retained checkpoint ONNX
# for existing validated deployments.
EXPORTED_ONNX="${A3_EXPORT_OUTPUT_DIR:-${EDGE_ROOT}/work/export}/onnx"
if [[ -n "${A3_ONNX_SOURCE_DIR:-}" ]]; then
  ONNX_SOURCE="$A3_ONNX_SOURCE_DIR"
elif [[ -f "${EXPORTED_ONNX}/export_metadata.json" ]]; then
  ONNX_SOURCE="$EXPORTED_ONNX"
else
  ONNX_SOURCE="${A3_MODEL_PATH}/onnx"
fi
OUTPUT_ROOT="${A3_BUILD_OUTPUT_DIR:-${EDGE_ROOT}/work/build}"
ONNX_LINK="${OUTPUT_ROOT}/onnx"
EMBODIMENT_TAG="${A3_EMBODIMENT_TAG:-${EMBODIMENT:-NEW_EMBODIMENT}}"

for required in export_metadata.json vit_fp32.onnx llm_bf16.onnx \
                vl_self_attention.onnx state_encoder.onnx \
                action_encoder.onnx dit_bf16.onnx dit_bf16.onnx.data \
                action_decoder.onnx; do
  if [[ ! -s "${ONNX_SOURCE}/${required}" ]]; then
    echo "[build] missing ONNX artifact: ${ONNX_SOURCE}/${required}" >&2
    exit 66
  fi
done

echo "[build] ONNX source: ${ONNX_SOURCE}"
echo "[build] engine output: ${OUTPUT_ROOT}/engines"
echo "[build] embodiment: ${EMBODIMENT_TAG}"

mkdir -p -- "${OUTPUT_ROOT}"
if [[ -L "${ONNX_LINK}" ]]; then
  if [[ "$(readlink -f -- "${ONNX_LINK}")" != "$(readlink -f -- "${ONNX_SOURCE}")" ]]; then
    echo "[build] ${ONNX_LINK} points to a different ONNX directory" >&2
    exit 65
  fi
elif [[ -e "${ONNX_LINK}" ]]; then
  echo "[build] ${ONNX_LINK} exists and is not a symlink" >&2
  exit 65
else
  ln -s -- "${ONNX_SOURCE}" "${ONNX_LINK}"
fi

exec bash "${A3_GR00T_ROOT}/scripts/deployment/export_a3_onnx_on_adu.sh" \
  --model-path "${A3_MODEL_PATH}" \
  --dataset-path dummy \
  --embodiment-tag "${EMBODIMENT_TAG}" \
  --output-dir "${OUTPUT_ROOT}" \
  --export-mode full_pipeline \
  --precision bf16 \
  --network-typing strong \
  --steps build \
  "$@"
