# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/common/planning.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/common/planning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'aimdk/protocol/mc/common/planning.proto\x12\x0e\x61imdk.protocol\"\x16\n\x14McPlanningWorldModel\"\x11\n\x0fMcPlanningScene*\xf9\x03\n\x0fMcPlanningGroup\x12\x1b\n\x17McPlanningGroup_UNKNOWN\x10\x00\x12\x1c\n\x18McPlanningGroup_LEFT_ARM\x10\x01\x12\"\n\x1eMcPlanningGroup_LEFT_ARM_WAIST\x10\x02\x12(\n$McPlanningGroup_LEFT_ARM_WAIST_WHEEL\x10\x03\x12\x1d\n\x19McPlanningGroup_RIGHT_ARM\x10\x04\x12#\n\x1fMcPlanningGroup_RIGHT_ARM_WAIST\x10\x05\x12)\n%McPlanningGroup_RIGHT_ARM_WAIST_WHEEL\x10\x06\x12\x1c\n\x18McPlanningGroup_DUAL_ARM\x10\x07\x12\"\n\x1eMcPlanningGroup_DUAL_ARM_WAIST\x10\x08\x12(\n$McPlanningGroup_DUAL_ARM_WAIST_WHEEL\x10\t\x12\'\n#McPlanningGroup_DUAL_ARM_WAIST_HEAD\x10\n\x12\x1e\n\x1aMcPlanningGroup_WAIST_LIFT\x10\x0b\x12\x1f\n\x1bMcPlanningGroup_WAIST_PITCH\x10\x0c\x12\x18\n\x14McPlanningGroup_HEAD\x10\r*\x9e\x01\n\x0eMcPlanningMode\x12\x1a\n\x16McPlanningMode_DEFAULT\x10\x00\x12\x1a\n\x16McPlanningMode_CLOSURE\x10\x64\x12\x18\n\x13McPlanningMode_GRAB\x10\xc8\x01\x12\x19\n\x14McPlanningMode_PLACE\x10\xac\x02\x12\x1f\n\x1aMcPlanningMode_LINEAR_MOVE\x10\x90\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.common.planning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MCPLANNINGGROUP']._serialized_start=103
  _globals['_MCPLANNINGGROUP']._serialized_end=608
  _globals['_MCPLANNINGMODE']._serialized_start=611
  _globals['_MCPLANNINGMODE']._serialized_end=769
  _globals['_MCPLANNINGWORLDMODEL']._serialized_start=59
  _globals['_MCPLANNINGWORLDMODEL']._serialized_end=81
  _globals['_MCPLANNINGSCENE']._serialized_start=83
  _globals['_MCPLANNINGSCENE']._serialized_end=100
# @@protoc_insertion_point(module_scope)
