# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/hal/neck/hal_neck_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/hal/neck/hal_neck_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import rpc_pb2 as aimdk_dot_protocol_dot_common_dot_rpc__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_rpc__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.hal.neck import neck_pb2 as aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.control_source_pb2
try:
  aimdk_dot_protocol_dot_common_dot_joint__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_joint__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_joint__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.joint_pb2
try:
  aimdk_dot_protocol_dot_common_dot_rpc__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_rpc__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_rpc__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.rpc_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_hal_dot_neck_dot_neck__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.rpc_pb2 import *
from aimdk.protocol.hal.neck.neck_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.aimdk/protocol/hal/neck/hal_neck_service.proto\x12\x0e\x61imdk.protocol\x1a\x1f\x61imdk/protocol/common/rpc.proto\x1a\"aimdk/protocol/hal/neck/neck.proto2\xb8\x01\n\x0eHalNeckService\x12P\n\x0cGetNeckState\x12\x1d.aimdk.protocol.CommonRequest\x1a!.aimdk.protocol.NeckStateResponse\x12T\n\x0eSetNeckCommand\x12\".aimdk.protocol.NeckCommandRequest\x1a\x1e.aimdk.protocol.CommonResponseP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.hal.neck.hal_neck_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HALNECKSERVICE']._serialized_start=136
  _globals['_HALNECKSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
