# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/sonic/sonic_token_channel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/sonic/sonic_token_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.aimdk/protocol/sonic/sonic_token_channel.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\"5\n\nSonicToken\x12\x10\n\x08stamp_ns\x18\x01 \x01(\x03\x12\x15\n\rencoded_token\x18\x02 \x03(\x02\"e\n\x11SonicTokenChannel\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.aimdk.protocol.Header\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1a.aimdk.protocol.SonicTokenP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.sonic.sonic_token_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONICTOKEN']._serialized_start=102
  _globals['_SONICTOKEN']._serialized_end=155
  _globals['_SONICTOKENCHANNEL']._serialized_start=157
  _globals['_SONICTOKENCHANNEL']._serialized_end=258
# @@protoc_insertion_point(module_scope)
