# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/hal/hand/agi_hand.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/hal/hand/agi_hand.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&aimdk/protocol/hal/hand/agi_hand.proto\x12\x0e\x61imdk.protocol\"\x81\x01\n\tFingerPos\x12\x13\n\x0bthumb_pos_0\x18\x01 \x01(\x05\x12\x13\n\x0bthumb_pos_1\x18\x02 \x01(\x05\x12\x11\n\tindex_pos\x18\x03 \x01(\x05\x12\x12\n\nmiddle_pos\x18\x04 \x01(\x05\x12\x10\n\x08ring_pos\x18\x05 \x01(\x05\x12\x11\n\tpinky_pos\x18\x06 \x01(\x05\"\x81\x01\n\tFingerToq\x12\x13\n\x0bthumb_toq_0\x18\x01 \x01(\x05\x12\x13\n\x0bthumb_toq_1\x18\x02 \x01(\x05\x12\x11\n\tindex_toq\x18\x03 \x01(\x05\x12\x12\n\nmiddle_toq\x18\x04 \x01(\x05\x12\x10\n\x08ring_toq\x18\x05 \x01(\x05\x12\x11\n\tpinky_toq\x18\x06 \x01(\x05\"_\n\rFingerCommand\x12&\n\x03pos\x18\x01 \x01(\x0b\x32\x19.aimdk.protocol.FingerPos\x12&\n\x03toq\x18\x02 \x01(\x0b\x32\x19.aimdk.protocol.FingerToq\"]\n\x0b\x46ingerState\x12&\n\x03pos\x18\x01 \x01(\x0b\x32\x19.aimdk.protocol.FingerPos\x12&\n\x03toq\x18\x02 \x01(\x0b\x32\x19.aimdk.protocol.FingerToq\"B\n\x11\x41gibotHandCommand\x12-\n\x06\x66inger\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.FingerCommand\">\n\x0f\x41gibotHandState\x12+\n\x06\x66inger\x18\x01 \x01(\x0b\x32\x1b.aimdk.protocol.FingerStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.hal.hand.agi_hand_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINGERPOS']._serialized_start=59
  _globals['_FINGERPOS']._serialized_end=188
  _globals['_FINGERTOQ']._serialized_start=191
  _globals['_FINGERTOQ']._serialized_end=320
  _globals['_FINGERCOMMAND']._serialized_start=322
  _globals['_FINGERCOMMAND']._serialized_end=417
  _globals['_FINGERSTATE']._serialized_start=419
  _globals['_FINGERSTATE']._serialized_end=512
  _globals['_AGIBOTHANDCOMMAND']._serialized_start=514
  _globals['_AGIBOTHANDCOMMAND']._serialized_end=580
  _globals['_AGIBOTHANDSTATE']._serialized_start=582
  _globals['_AGIBOTHANDSTATE']._serialized_end=644
# @@protoc_insertion_point(module_scope)
