# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/data/arm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/data/arm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.mc.common import arm_pb2 as aimdk_dot_protocol_dot_mc_dot_common_dot_arm__pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.mc.common.arm_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n aimdk/protocol/mc/data/arm.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a\"aimdk/protocol/mc/common/arm.proto\"n\n\tArmStatus\x12\x12\n\nerror_code\x18\x01 \x01(\x08\x12\r\n\x05inpos\x18\x02 \x01(\x08\x12\x0e\n\x06\x65nable\x18\x03 \x01(\x08\x12\x17\n\x0fprotective_stop\x18\x04 \x01(\x08\x12\x15\n\ron_soft_limit\x18\x05 \x01(\x08\"l\n\x10\x41rmStatusRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12)\n\x08\x61rm_type\x18\x02 \x01(\x0e\x32\x17.aimdk.protocol.ArmType\"r\n\x11\x41rmStatusResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12-\n\narm_status\x18\x02 \x01(\x0b\x32\x19.aimdk.protocol.ArmStatusP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.data.arm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARMSTATUS']._serialized_start=124
  _globals['_ARMSTATUS']._serialized_end=234
  _globals['_ARMSTATUSREQUEST']._serialized_start=236
  _globals['_ARMSTATUSREQUEST']._serialized_end=344
  _globals['_ARMSTATUSRESPONSE']._serialized_start=346
  _globals['_ARMSTATUSRESPONSE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
