# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/data/joint.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/data/joint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.common import joint_pb2 as aimdk_dot_protocol_dot_common_dot_joint__pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.common.joint_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"aimdk/protocol/mc/data/joint.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a!aimdk/protocol/common/joint.proto\"s\n\x15McJointStatesResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12*\n\x06states\x18\x02 \x03(\x0b\x32\x1a.aimdk.protocol.JointState\"y\n\x17McJointCommandsResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12.\n\x08\x63ommands\x18\x02 \x03(\x0b\x32\x1c.aimdk.protocol.JointCommand\"s\n\x15McJointParamsResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.aimdk.protocol.JointParam\"1\n\x0fMcJointPosition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x01\"x\n\x15McJointAnglesResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12/\n\x06joints\x18\x02 \x03(\x0b\x32\x1f.aimdk.protocol.McJointPositionP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.data.joint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MCJOINTSTATESRESPONSE']._serialized_start=125
  _globals['_MCJOINTSTATESRESPONSE']._serialized_end=240
  _globals['_MCJOINTCOMMANDSRESPONSE']._serialized_start=242
  _globals['_MCJOINTCOMMANDSRESPONSE']._serialized_end=363
  _globals['_MCJOINTPARAMSRESPONSE']._serialized_start=365
  _globals['_MCJOINTPARAMSRESPONSE']._serialized_end=480
  _globals['_MCJOINTPOSITION']._serialized_start=482
  _globals['_MCJOINTPOSITION']._serialized_end=531
  _globals['_MCJOINTANGLESRESPONSE']._serialized_start=533
  _globals['_MCJOINTANGLESRESPONSE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
