# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/mc/data/mgpt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/mc/data/mgpt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!aimdk/protocol/mc/data/mgpt.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\"u\n\x15MotionGPTStateRequest\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.aimdk.protocol.RequestHeader\x12-\n\x05state\x18\x02 \x01(\x0e\x32\x1e.aimdk.protocol.MotionGPTState\"w\n\x16MotionGPTStateResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.aimdk.protocol.ResponseHeader\x12-\n\x05state\x18\x02 \x01(\x0e\x32\x1e.aimdk.protocol.MotionGPTState*\xfc\x01\n\x0eMotionGPTState\x12$\n MotionGPTState_WAIT_MGPT_COMMAND\x10\x00\x12(\n$MotionGPTState_MOVING_TO_FIRST_POINT\x10\x01\x12&\n\"MotionGPTState_ARRIVED_FIRST_POINT\x10\x02\x12(\n$MotionGPTState_MOVING_TO_FINAL_POINT\x10\x03\x12&\n\"MotionGPTState_ARRIVED_FINAL_POINT\x10\x04\x12 \n\x1cMotionGPTState_MGPT_FINISHED\x10\x05P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.mc.data.mgpt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONGPTSTATE']._serialized_start=330
  _globals['_MOTIONGPTSTATE']._serialized_end=582
  _globals['_MOTIONGPTSTATEREQUEST']._serialized_start=89
  _globals['_MOTIONGPTSTATEREQUEST']._serialized_end=206
  _globals['_MOTIONGPTSTATERESPONSE']._serialized_start=208
  _globals['_MOTIONGPTSTATERESPONSE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
