# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/common/control_source.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/common/control_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*aimdk/protocol/common/control_source.proto\x12\x0e\x61imdk.protocol*v\n\rControlSource\x12\x16\n\x12\x43ontrolSource_AUTO\x10\x00\x12\x18\n\x14\x43ontrolSource_MANUAL\x10\x01\x12\x16\n\x12\x43ontrolSource_SAFE\x10\x02\x12\x1b\n\x16\x43ontrolSource_DISABLED\x10\xff\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.common.control_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLSOURCE']._serialized_start=62
  _globals['_CONTROLSOURCE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
