# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/common/header.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/common/header.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import timestamp_pb2 as aimdk_dot_protocol_dot_common_dot_timestamp__pb2
from aimdk.protocol.common import control_source_pb2 as aimdk_dot_protocol_dot_common_dot_control__source__pb2

from aimdk.protocol.common.timestamp_pb2 import *
from aimdk.protocol.common.control_source_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"aimdk/protocol/common/header.proto\x12\x0e\x61imdk.protocol\x1a%aimdk/protocol/common/timestamp.proto\x1a*aimdk/protocol/common/control_source.proto\"\x9a\x01\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12,\n\ttimestamp\x18\x02 \x01(\x0b\x32\x19.aimdk.protocol.Timestamp\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x12\x35\n\x0e\x63ontrol_source\x18\x04 \x01(\x0e\x32\x1d.aimdk.protocol.ControlSource\x12\x0c\n\x04uuid\x18\x05 \x01(\t\"\xa3\x01\n\rRequestHeader\x12,\n\ttimestamp\x18\x01 \x01(\x0b\x32\x19.aimdk.protocol.Timestamp\x12\x35\n\x0e\x63ontrol_source\x18\x02 \x01(\x0e\x32\x1d.aimdk.protocol.ControlSource\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\r\n\x05\x64omin\x18\x05 \x01(\t\"z\n\x0eResponseHeader\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x04\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12,\n\ttimestamp\x18\x03 \x01(\x0b\x32\x19.aimdk.protocol.Timestamp\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\r\n\x05\x64omin\x18\x05 \x01(\t\"\xbd\x01\n\x16\x42lockableRequestHeader\x12,\n\ttimestamp\x18\x01 \x01(\x0b\x32\x19.aimdk.protocol.Timestamp\x12\x0f\n\x07\x62locked\x18\x02 \x01(\x08\x12\x35\n\x0e\x63ontrol_source\x18\x03 \x01(\x0e\x32\x1d.aimdk.protocol.ControlSource\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\r\n\x05\x64omin\x18\x06 \x01(\t\"\x8f\x01\n\x17\x42lockableResponseHeader\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x04\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12,\n\ttimestamp\x18\x03 \x01(\x0b\x32\x19.aimdk.protocol.Timestamp\x12\n\n\x02id\x18\x04 \x01(\x04\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\r\n\x05\x64omin\x18\x06 \x01(\tP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.common.header_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=138
  _globals['_HEADER']._serialized_end=292
  _globals['_REQUESTHEADER']._serialized_start=295
  _globals['_REQUESTHEADER']._serialized_end=458
  _globals['_RESPONSEHEADER']._serialized_start=460
  _globals['_RESPONSEHEADER']._serialized_end=582
  _globals['_BLOCKABLEREQUESTHEADER']._serialized_start=585
  _globals['_BLOCKABLEREQUESTHEADER']._serialized_end=774
  _globals['_BLOCKABLERESPONSEHEADER']._serialized_start=777
  _globals['_BLOCKABLERESPONSEHEADER']._serialized_end=920
# @@protoc_insertion_point(module_scope)
