# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/ta/ta_whole_body_state.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/ta/ta_whole_body_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.common import joint_pb2 as aimdk_dot_protocol_dot_common_dot_joint__pb2
from aimdk.protocol.ta import ta_whole_body_command_pb2 as aimdk_dot_protocol_dot_ta_dot_ta__whole__body__command__pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.common.joint_pb2 import *
from aimdk.protocol.ta.ta_whole_body_command_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+aimdk/protocol/ta/ta_whole_body_state.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a!aimdk/protocol/common/joint.proto\x1a-aimdk/protocol/ta/ta_whole_body_command.proto\"?\n\x11TaJointGroupState\x12*\n\x06states\x18\x01 \x03(\x0b\x32\x1a.aimdk.protocol.JointState\"j\n\nTaImuState\x12\x15\n\tquat_wxyz\x18\x01 \x03(\x01\x42\x02\x10\x01\x12 \n\x14\x61ngular_velocity_xyz\x18\x02 \x03(\x01\x42\x02\x10\x01\x12#\n\x17linear_acceleration_xyz\x18\x03 \x03(\x01\x42\x02\x10\x01\"\x81\x03\n\x10TaWholeBodyState\x12\x33\n\x0cjoint_layout\x18\x01 \x01(\x0e\x32\x1d.aimdk.protocol.TaJointLayout\x12\x34\n\tleg_state\x18\x04 \x01(\x0b\x32!.aimdk.protocol.TaJointGroupState\x12\x36\n\x0bwaist_state\x18\x06 \x01(\x0b\x32!.aimdk.protocol.TaJointGroupState\x12\x35\n\nhead_state\x18\x07 \x01(\x0b\x32!.aimdk.protocol.TaJointGroupState\x12\x34\n\tarm_state\x18\x08 \x01(\x0b\x32!.aimdk.protocol.TaJointGroupState\x12.\n\npelvis_imu\x18\x0b \x01(\x0b\x32\x1a.aimdk.protocol.TaImuState\x12-\n\ttorso_imu\x18\x0c \x01(\x0b\x32\x1a.aimdk.protocol.TaImuState\"q\n\x17TaWholeBodyStateChannel\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.aimdk.protocol.Header\x12.\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32 .aimdk.protocol.TaWholeBodyStateP\x00P\x01P\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.ta.ta_whole_body_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAIMUSTATE'].fields_by_name['quat_wxyz']._loaded_options = None
  _globals['_TAIMUSTATE'].fields_by_name['quat_wxyz']._serialized_options = b'\020\001'
  _globals['_TAIMUSTATE'].fields_by_name['angular_velocity_xyz']._loaded_options = None
  _globals['_TAIMUSTATE'].fields_by_name['angular_velocity_xyz']._serialized_options = b'\020\001'
  _globals['_TAIMUSTATE'].fields_by_name['linear_acceleration_xyz']._loaded_options = None
  _globals['_TAIMUSTATE'].fields_by_name['linear_acceleration_xyz']._serialized_options = b'\020\001'
  _globals['_TAJOINTGROUPSTATE']._serialized_start=181
  _globals['_TAJOINTGROUPSTATE']._serialized_end=244
  _globals['_TAIMUSTATE']._serialized_start=246
  _globals['_TAIMUSTATE']._serialized_end=352
  _globals['_TAWHOLEBODYSTATE']._serialized_start=355
  _globals['_TAWHOLEBODYSTATE']._serialized_end=740
  _globals['_TAWHOLEBODYSTATECHANNEL']._serialized_start=742
  _globals['_TAWHOLEBODYSTATECHANNEL']._serialized_end=855
# @@protoc_insertion_point(module_scope)
