# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aimdk/protocol/motion_control/motion/mc_motion_channel.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aimdk/protocol/motion_control/motion/mc_motion_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aimdk.protocol.common import header_pb2 as aimdk_dot_protocol_dot_common_dot_header__pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_common_dot_header__pb2.aimdk.protocol.common.control_source_pb2
from aimdk.protocol.motion_control.motion import locomotion_pb2 as aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2
try:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk_dot_protocol_dot_common_dot_header__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_header__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk.protocol.common.header_pb2
try:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk_dot_protocol_dot_common_dot_timestamp__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_timestamp__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk.protocol.common.timestamp_pb2
try:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk_dot_protocol_dot_common_dot_control__source__pb2
except AttributeError:
  aimdk_dot_protocol_dot_common_dot_control__source__pb2 = aimdk_dot_protocol_dot_motion__control_dot_motion_dot_locomotion__pb2.aimdk.protocol.common.control_source_pb2

from aimdk.protocol.common.header_pb2 import *
from aimdk.protocol.motion_control.motion.locomotion_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<aimdk/protocol/motion_control/motion/mc_motion_channel.proto\x12\x0e\x61imdk.protocol\x1a\"aimdk/protocol/common/header.proto\x1a\x35\x61imdk/protocol/motion_control/motion/locomotion.proto\"\x8f\x01\n&MotionControlLocomotionVelocityChannel\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.aimdk.protocol.Header\x12=\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32/.aimdk.protocol.MotionControlLocomotionVelocity\"\x99\x01\n\x1dMotionControlMoveWaistChannel\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.aimdk.protocol.Header\x12\x13\n\x0bwaist_pitch\x18\x02 \x01(\x01\x12\x12\n\nwaist_roll\x18\x03 \x01(\x01\x12\x11\n\twaist_yaw\x18\x04 \x01(\x01\x12\x14\n\x0cwaist_height\x18\x05 \x01(\x01P\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aimdk.protocol.motion_control.motion.mc_motion_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONCONTROLLOCOMOTIONVELOCITYCHANNEL']._serialized_start=172
  _globals['_MOTIONCONTROLLOCOMOTIONVELOCITYCHANNEL']._serialized_end=315
  _globals['_MOTIONCONTROLMOVEWAISTCHANNEL']._serialized_start=318
  _globals['_MOTIONCONTROLMOVEWAISTCHANNEL']._serialized_end=471
# @@protoc_insertion_point(module_scope)
